### PR TITLE
Fix the build for Mac

### LINKED ISSUE #64: Preserving file permissions (especially executable bits)?
I'm not sure if it's just me or if there is a bug/limitation in this library. Based off the sample code given in library docs, here's what I wrote:

```
do
  bs <- BS.readFile "/tmp/some-executable-binary"
  s <- Zip.mkEntrySelector "some-executable-binary"
  Zip.createArchive "/tmp/zipfile.zip" (Zip.addEntry Zip.Deflate bs s)
```

This creates `/tmp/zipfile.zip`, **but when it is unzipped, `some-executable-binary` no longer has an executable bit set.**

After that, I tried making the following change...

```
  s <- Zip.mkEntrySelector "/tmp/some-executable-binary"
```

**...but it gave the following error:**

```
*** Exception: Cannot build selector from "/tmp/bootstrap"
```

What am I doing wrong?

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #64.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Please see if this fixes the issue for you, @saurabhnanda.

**Comment by mrkkrp** [comment]
Ping @saurabhnanda.

**Comment by saurabhnanda** [comment]
@mrkkrp I can confirm that this fixes the build on Mac OS. Thank you 👍 

```
[LOCALHOST:/tmp/zip ((2b9ea0b...)) saurabhnanda] $ stack init  --resolver=lts-12.1
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selected resolver: lts-12.1
Initialising configuration using resolver: lts-12.1
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
[LOCALHOST:/tmp/zip ((2b9ea0b...)) saurabhnanda] $ stack build
Building all executables for `zip' once. After a successful build of all of them, only specified executables will be rebuilt.
zip> configure (lib + exe)
Configuring zip-1.4.0...
zip> build (lib + exe)
Preprocessing library for zip-1.4.0..
Building library for zip-1.4.0..
[1 of 5] Compiling Codec.Archive.Zip.CP437
[2 of 5] Compiling Codec.Archive.Zip.Type
[3 of 5] Compiling Codec.Archive.Zip.Internal
[4 of 5] Compiling Codec.Archive.Zip
[5 of 5] Compiling Codec.Archive.Zip.Unix
ignoring (possibly broken) abi-depends field for packages
Preprocessing executable 'haskell-zip-app' for zip-1.4.0..
Building executable 'haskell-zip-app' for zip-1.4.0..
[1 of 1] Compiling Main
Linking .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/haskell-zip-app/haskell-zip-app ...
zip> copy/register
Installing library in /private/tmp/zip/.stack-work/install/x86_64-osx/7f84ca1c9df0fba1e31f23d015cf9ec2d886a8c00f06a7733000f2b2df6ef820/8.4.3/lib/x86_64-osx-ghc-8.4.3/zip-1.4.0-GBDXktJf7APETPN3LlXJeI
Installing executable haskell-zip-app in /private/tmp/zip/.stack-work/install/x86_64-osx/7f84ca1c9df0fba1e31f23d015cf9ec2d886a8c00f06a7733000f2b2df6ef820/8.4.3/bin
Registering library for zip-1.4.0..
```

**Comment by mrkkrp** [comment]
Let's merge it in, then.

**Comment by mrkkrp** [comment]
Published 1.4.1.

**Pull request merged**
