### PR TITLE
Let me see if the CI is still broken

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by mrkkrp** [comment]
I just deleted all caches.

**Comment by phadej** [comment]
Sad, then I won't see if error reporting have improved.

**Comment by mrkkrp** [comment]
Ah, sorry. I just remember you said that the problem should be fixed if I clear the caches, that's why I did it.

**Comment by phadej** [comment]
No worries, I tried to be quick and see what was actually broken. But maybe next itme. At least builds seem to go past the failure point, so the issue is resolved for now.

**Pull request closed without merging**
